/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LocationBtn: typeof import('./src/components/LocationBtn.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    SaveLocationBtn: typeof import('./src/components/SaveLocationBtn.vue')['default']
  }
}
